name = "ForwardNeuralNetworks"
uuid = "41bbd1a4-0eca-4bcd-b6b1-8656d032eaeb"
version = "0.2.1"
authors = ["ngiann <ngiann@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
